-- ─── Migration 0002: Update entity catalog with real Maestro names ─────────────
-- Run this on the production MySQL database once.
-- It is safe to run multiple times (uses ON DUPLICATE KEY UPDATE / INSERT IGNORE).

-- ─── 1. Update existing entries with full names from the Maestro ─────────────

UPDATE entidades SET nombres_raw = '["SANITAS","EPS SANITAS","ENTIDAD PROMOTORA DE SALUD SANITAS","SASEN"]'
WHERE nombre = 'SANITAS';

UPDATE entidades SET nombres_raw = '["SURAMERICANA","EPS SURAMERICANA","EPS SURAMERICANA SA","SEGUROS DE VIDA SURAMERICANA","SURAMERCIANA","EPS SURA"]'
WHERE nombre = 'SURAMERICANA';

UPDATE entidades SET nombres_raw = '["NUEVA EPS","NUEVAEPS","NUEVA EPS SA"]'
WHERE nombre = 'NUEVA EPS';

UPDATE entidades SET nombres_raw = '["FAMISANAR","FAMISANAR LTDA"]'
WHERE nombre = 'FAMISANAR';

UPDATE entidades SET nombres_raw = '["COMPENSAR","COMPENSAR EPS"]'
WHERE nombre = 'COMPENSAR';

UPDATE entidades SET nombres_raw = '["MEDIMAS","MÉDIMAS","MEDIMAS EPS"]'
WHERE nombre = 'MEDIMAS';

UPDATE entidades SET nombres_raw = '["ALIANSALUD","ALIAN SALUD","ALIANSALUD EPS"]'
WHERE nombre = 'ALIANSALUD';

UPDATE entidades SET nombres_raw = '["COMFAMILIAR","COMFAMILIAR RISARALDA","CAJA DE COMPENSACION FAMILIAR DE RISARALDA"]'
WHERE nombre = 'COMFAMILIAR';

UPDATE entidades SET nombres_raw = '["VIVA 1A","VIVA1A","VIVA","VIVA 1A EPS"]'
WHERE nombre = 'VIVA 1A';

UPDATE entidades SET nombres_raw = '["PARTICULARES","PARTICULAR","PART","PARTICULARES/CONVENIOS","PACIENTE PARTICULAR"]'
WHERE nombre = 'PARTICULARES';

UPDATE entidades SET nombres_raw = '["CONVENIO EMPRESARIAL","CONVENIO","CONVENIO CM","CONVENIO CM PLUS","CONVENIOS"]'
WHERE nombre = 'CONVENIO EMPRESARIAL';

UPDATE entidades SET nombres_raw = '["DALELA","DALELA1130","DALELA IPS"]'
WHERE nombre = 'DALELA';

-- ─── 2. Delete duplicate PARTICULAR entry (keep PARTICULARES) ────────────────
DELETE FROM entidades WHERE nombre = 'PARTICULAR' AND id = 'a14a9455-d588-4e1e-aa33-aab2d38e50ef';

-- ─── 3. Insert new entities ───────────────────────────────────────────────────

INSERT IGNORE INTO entidades (id, nombre, nombres_raw, tipo, es_grupo_caja, activa, created_at) VALUES
  -- EPS (régimen contributivo / subsidiado)
  (UUID(), 'COMFENALCO VALLE', '["COMFENALCO","COMFENALCO VALLE","CAJA DE COMPENSACION FAMILIAR DEL VALLE"]', 'EPS', 0, 1, NOW()),
  (UUID(), 'SERVICIO OCCIDENTAL DE SALUD', '["SERVICIO OCCIDENTAL","SOS SALUD","OCCIDENTAL DE SALUD"]', 'EPS', 0, 1, NOW()),
  (UUID(), 'SALUD TOTAL', '["SALUD TOTAL","SALUD TOTAL SA","SALUD TOTAL EPS"]', 'EPS', 0, 1, NOW()),

  -- Medicina prepagada / seguros
  (UUID(), 'COLMEDICA', '["COLMEDICA","COLMEDICA MEDICINA PREPAGADA","COLMEDICA LINEA"]', 'PREPAGADA', 0, 1, NOW()),
  (UUID(), 'COOMEVA', '["COOMEVA","COOMEVA MEDICINA PREPAGADA","COOMEVA EPS"]', 'PREPAGADA', 0, 1, NOW()),
  (UUID(), 'MEDISANITAS', '["MEDISANITAS","MEDISANITAS SA","MEDISANITAS MEDICINA PREPAGADA"]', 'PREPAGADA', 0, 1, NOW()),
  (UUID(), 'COLSANITAS', '["COLSANITAS","COLSANITAS SA","COLSANITAS MEDICINA PREPAGADA"]', 'PREPAGADA', 0, 1, NOW()),
  (UUID(), 'AXA COLPATRIA', '["AXA COLPATRIA","COLPATRIA","AXA COLPATRIA MEDICINA PREPAGADA","AXA COLPATRIA SEGUROS"]', 'PREPAGADA', 0, 1, NOW()),
  (UUID(), 'MEDPLUS', '["MEDPLUS","MEDPLUS MEDICINA PREPAGADA","MEDPLUS SA"]', 'PREPAGADA', 0, 1, NOW()),
  (UUID(), 'PROTEGEMOS', '["PROTEGEMOS","PROTEGEMOS SA"]', 'PREPAGADA', 0, 1, NOW()),
  (UUID(), 'SEGUROS BOLIVAR', '["SEGUROS BOLIVAR","COMPANIA DE SEGUROS BOLIVAR","BOLIVAR SEGUROS"]', 'PREPAGADA', 0, 1, NOW()),

  -- Convenios institucionales
  (UUID(), 'ALIANZA ESTRATEGICAS', '["ALIANZA ESTRATEGICAS","ALIANZA ESTRATEG","ALIANZAS ESTRATEGICAS EN SERVICIOS"]', 'CONVENIO', 0, 1, NOW()),
  (UUID(), 'ALIANZAS VIP', '["ALIANZAS VIP","ALIANZA VIP"]', 'CONVENIO', 0, 1, NOW()),
  (UUID(), 'CLINICA DE OCCIDENTE', '["CLINICA DE OCCIDENTE","CLINICA OCCIDENTE","CLINICA DE OCCIDENTE SA"]', 'CONVENIO', 0, 1, NOW()),
  (UUID(), 'CLINICA VERSALLES', '["CLINICA VERSALLES","VERSALLES SA","CLINICA VERSALLES SA"]', 'CONVENIO', 0, 1, NOW()),
  (UUID(), 'UNISALUD UNAL', '["UNISALUD","UNISALUD UNAL","UNISALUD UNIVERSIDAD"]', 'CONVENIO', 0, 1, NOW()),
  (UUID(), 'ECOPETROL', '["ECOPETROL","ECOPETROL SA"]', 'CONVENIO', 0, 1, NOW()),
  (UUID(), 'UNIDAD SALUD OCUPACIONAL', '["UNIDAD DE SALUD OCUPACIONAL","OCUPACIONALSAS","UNIDAD SALUD OCUPACIONAL"]', 'CONVENIO', 0, 1, NOW()),
  (UUID(), 'UNIDAD MEDICA LER', '["UNIDAD MEDICA LER","MEDICA LER"]', 'CONVENIO', 0, 1, NOW()),
  (UUID(), 'INSTITUTO RELIGIOSAS SAN JOSE', '["INSTITUTO DE RELIGIOSAS","SAN JOSE DE GERONA","RELIGIOSAS SAN JOSE"]', 'CONVENIO', 0, 1, NOW()),
  (UUID(), 'IPS SOLUCIONES MEDICAS', '["IPS SOLUCIONES MEDICAS","SOLUCIONES MEDICAS EN SALUD"]', 'CONVENIO', 0, 1, NOW()),
  (UUID(), 'IPS OCUPACIONAL SANTA CLARA', '["OCUPACIONAL SANTA CLARA","IPS OCUPACIONAL SANTA CLARA"]', 'CONVENIO', 0, 1, NOW()),
  (UUID(), 'CENTRO MEDICO MEDISALUD', '["MEDISALUD IPS","CENTRO MEDICO MEDISALUD","MEDISALUD SAS"]', 'CONVENIO', 0, 1, NOW()),
  (UUID(), 'OMNI SALUD', '["MEDICO ODONTOLOGICA NACIONAL","OMNI","ORGANIZACION MEDICO ODONTOLOGICA"]', 'CONVENIO', 0, 1, NOW()),
  (UUID(), 'FIDUCIARIA PREVISORA FOMAG', '["FIDUCIARIA LA PREVISORA","FOMAG","PREVISORA SA FOMAG"]', 'CONVENIO', 0, 1, NOW()),
  (UUID(), 'TARJETA LA MEDICA', '["TARJETA LA MEDICA","LA MEDICA TARJETA"]', 'CONVENIO', 0, 1, NOW()),
  (UUID(), 'COSERSSA', '["COSERSSA"]', 'CONVENIO', 0, 1, NOW()),
  (UUID(), 'TSERVIMOS', '["TSERVIMOS"]', 'CONVENIO', 0, 1, NOW()),
  (UUID(), 'GLADYS GOMEZ BERMEO', '["GLADYS GOMEZ BERMEO","GLADYS GOMEZ"]', 'CONVENIO', 0, 1, NOW());
