CREATE TABLE `liquidacion_ajustes` (
  `id`              VARCHAR(36)   NOT NULL DEFAULT (UUID()),
  `liquidacion_id`  VARCHAR(36)   NOT NULL,
  `categoria`       VARCHAR(50)   NOT NULL,
  `descripcion`     VARCHAR(255)  NOT NULL,
  `cantidad`        INT           NOT NULL DEFAULT 1,
  `valor_unitario`  DECIMAL(12,2) NOT NULL,
  `valor_total`     DECIMAL(12,2) NOT NULL DEFAULT 0,
  `justificacion`   TEXT          NOT NULL,
  `referencia_doc`  VARCHAR(255)  NULL,
  `estado`          ENUM('PENDIENTE','AUTORIZADO','RECHAZADO') NOT NULL DEFAULT 'PENDIENTE',
  `creado_por`      VARCHAR(36)   NOT NULL,
  `creado_por_nombre` VARCHAR(200) NULL,
  `autorizado_por`  VARCHAR(36)   NULL,
  `autorizado_por_nombre` VARCHAR(200) NULL,
  `autorizado_en`   DATETIME      NULL,
  `motivo_rechazo`  TEXT          NULL,
  `created_at`      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_aj_liquidacion` (`liquidacion_id`),
  KEY `idx_aj_estado` (`estado`),
  CONSTRAINT `fk_aj_liquidacion` FOREIGN KEY (`liquidacion_id`) REFERENCES `liquidaciones` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
